name: Create and Setup SWA Infrastructure

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

env:
  ResourceGroup: rg-sdilab2
  Region: westeurope

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "test=hello" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}

  createSWA:
    name: Ensure SWA is Created
    runs-on: ubuntu-latest
    outputs:
      swaName: ${{ steps.createSWA.outputs.swaName }}
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: Az CLI login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create SWA
        id: createSWA
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az group create -n $ResourceGroup -l $Region
            res=$(az deployment group create \
              --resource-group $ResourceGroup \
              --template-file 'Templates/main.bicep' \
              --parameters 'Environments/development.parameters.json' \
              --query 'properties.outputs.swaName.value')
            echo "swaName=$res" >> $GITHUB_OUTPUT

      - name: Write value
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            echo "The name is: ${{ steps.createSWA.outputs.swaName }}"

  listSWA:
    name: List SWA
    runs-on: ubuntu-latest
    needs: createSWA
    env:
      swaName: ${{ needs.createSWA.outputs.swaName }}
    steps:

      - name: Write value
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            echo "The name is: $swaName"