name: Create and Setup SWA Infrastructure

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

env:
  ResourceGroup: rg-sdilab
  Region: swedencentral

jobs:
  swa-create:
    name: Ensure SWA is Created
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: Az CLI login
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create SWA
        id: create-swa
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            az group create -n $ResourceGroup -l $Region
            result = $( az deployment group create \
              --resource-group $ResourceGroup \
              --template-file Templates\main.bicep \
              --template-parameters-file Environments\development.parameters.json )
            echo "The result is: $result"
            echo "swa-name=$(result | ConvertFrom-Json).properties.outputs.swaName.value" >> "$GITHUB_OUTPUT"
            # echo "::set-output name=swa-name::$(output | ConvertFrom-Json).properties.outputs.swaName.value"

      - name: Write value
        uses: azure/CLI@v1
        with:
          azcliversion: 2.42.0
          inlineScript: |
            echo "The name is: ${{ steps.create-swa.outputs.swa-name }}"